name: Build NextDNS Docker Image
on:
  schedule:
    - cron: '* 2 * * *'

jobs:
  getNextDnsVersion:
    runs-on: ubuntu-latest
    outputs:
      current_tag: ${{ steps.nextdns-cli.outputs.current_tag }}
      release_tag: ${{ steps.nextdns-cli.outputs.release_tag }}
      nextdns_version: ${{ steps.nextdns-cli.outputs.nextdns_version }}
    steps:
      - name: Get Latest NextDNS CLI Release
        id: nextdns-cli
        run: |
          echo ::set-output name=release_tag::$(curl -sL https://api.github.com/repos/nextdns/nextdns/releases/latest | jq -r ".tag_name")
          echo ::set-output name=current_tag::$(curl -sL https://api.github.com/repos/adhodgson1/docker-nextdns/releases/latest | jq -r ".tag_name")
          echo ::set-output name=nextdns-version::$(echo ${{ release_tag }} | sed 's/v//')
      - name: Push Tag
        if: steps.nextdns-cli.outputs.current_tag != steps.nextdns-cli.outputs.release_tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.nextdns-cli.outputs.release_tag }}
      - name: Create a GitHub release
        if: steps.nextdns-cli.outputs.current_tag != steps.nextdns-cli.outputs.release_tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.nextdns-cli.outputs.release_tag }}
          release_name: Release ${{ steps.nextdns-cli.outputs.release_tag }}
          body: Upgrade NextDNS CLI to ${{ steps.nextdns-cli.outputs.release_tag }}

  buildNextDNSImage:
    runs-on: ubuntu-latest
    needs: getNextDnsVersion
    if: needs.getNextDnsVersion.outputs.current_tag != needs.getNextDnsVersion.outputs.release_tag
    env:
      NEXTDNS_VERSION: ${{ needs.getNextDnsVersion.outputs.nextdns_version }}
      IMAGE_NAME: adhodgson1/nextdns
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            NEXTDNS_VERSION: ${{ env.NEXTDNS_VERSION }}
          push: true
          tags: ${{ env.IMAGE_NAME }}/latest, ${{ env.IMAGE_NAME }}/${{ env.NEXTDNS_VERSION }}
